### ISSUE TITLE
一直提示需要 .net

### ISSUE THREAD

**Issue by R2h1** [laosanyuan/HuoHuan#5]

**Comment by laosanyuan** [comment]
应该是本地.net版本过低，可以尝试安装以下更新版本：https://dotnet.microsoft.com/zh-cn/download/dotnet-framework

**Comment by R2h1** [comment]
***@***.***的自动回复邮件。已收到您的邮件！

**Comment by R2h1** [comment]
好的谢谢

**Comment by laosanyuan** [comment]
> 好的谢谢

不客气，有使用问题欢迎提出
